import pptxgen from 'pptxgenjs';

/**
 * Generate a PowerPoint presentation from markdown content
 * 
 * @param title Title of the presentation
 * @param contentType Type of content being presented
 * @param content Markdown content
 * @returns PowerPoint presentation object
 */
export function generatePptx(title: string, contentType: string, content: string) {
  // Create a new PowerPoint presentation
  const pres = new pptxgen();
  
  // Set presentation properties
  pres.layout = 'LAYOUT_16x9';
  pres.title = title;
  pres.subject = contentType;
  pres.company = 'Generated by Sales Enablement Resource Center';
  
  // Create title slide
  const titleSlide = pres.addSlide();
  
  // Add a gradient background
  titleSlide.background = { 
    color: '2563EB', // blue-600
    type: 'solid' 
  };
  
  // Add title
  titleSlide.addText(title, { 
    x: 0.5, 
    y: 1.5, 
    w: '90%', 
    h: 1.5,
    align: 'center',
    color: 'FFFFFF',
    fontFace: 'Arial',
    fontSize: 44,
    bold: true
  });
  
  // Add subtitle
  titleSlide.addText(`${contentType}`, { 
    x: 0.5, 
    y: 3.3, 
    w: '90%', 
    h: 0.8, 
    align: 'center',
    color: 'FFFFFF',
    fontFace: 'Arial',
    fontSize: 24
  });
  
  // Add date
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  
  titleSlide.addText(dateStr, { 
    x: 0.5, 
    y: 7.5, 
    w: '90%', 
    h: 0.5, 
    align: 'center',
    color: 'FFFFFF',
    fontFace: 'Arial',
    fontSize: 16
  });
  
  // Parse the markdown content and create slides
  parseMarkdownToSlides(pres, content);
  
  return pres;
}

/**
 * Convert markdown content to PowerPoint slides
 * 
 * @param pres PowerPoint presentation object
 * @param markdown Markdown content
 */
function parseMarkdownToSlides(pres: pptxgen, markdown: string) {
  // Split the markdown by heading 2 (##) to create main sections
  const sections = markdown.split(/^## /m);
  
  for (let i = 0; i < sections.length; i++) {
    const section = sections[i].trim();
    if (!section) continue;
    
    // For the first section, it may not start with ## originally
    const sectionTitle = i === 0 && !sections[0].startsWith('#') 
      ? 'Overview'
      : section.split('\n')[0].trim();
    
    const sectionContent = i === 0 && !sections[0].startsWith('#')
      ? section
      : section.split('\n').slice(1).join('\n').trim();
    
    // Create section slide
    const sectionSlide = pres.addSlide();
    
    // Add section title
    sectionSlide.addText(sectionTitle, { 
      x: 0.5, 
      y: 0.5, 
      w: '90%', 
      h: 1,
      align: 'left',
      color: '2563EB', // blue-600
      fontFace: 'Arial',
      fontSize: 36,
      bold: true
    });
    
    // Add accent line
    sectionSlide.addShape(pptxgen.ShapeType.rect, { 
      x: 0.5, 
      y: 1.6, 
      w: 3, 
      h: 0.1,
      fill: { color: '2563EB' }
    });
    
    // Split section content by heading 3 (###) to create subsections
    const subSections = sectionContent.split(/^### /m);
    
    // Process the content without headings first
    const mainContent = subSections[0].trim();
    if (mainContent) {
      // Extract bullet points for the section slide
      const bulletPoints = extractBulletPoints(mainContent);
      
      if (bulletPoints.length > 0) {
        sectionSlide.addText(bulletPoints.map(point => point.trim()), { 
          x: 0.5, 
          y: 2.2, 
          w: '90%', 
          h: 4,
          align: 'left',
          color: '000000',
          fontFace: 'Arial',
          fontSize: 18,
          bullet: true
        });
      } else {
        // If no bullet points, add paragraphs
        const paragraphs = mainContent.split('\n\n').filter(Boolean);
        
        sectionSlide.addText(paragraphs.join('\n\n'), { 
          x: 0.5, 
          y: 2.2, 
          w: '90%', 
          h: 4,
          align: 'left',
          color: '000000',
          fontFace: 'Arial',
          fontSize: 18
        });
      }
    }
    
    // Process subsections (heading 3)
    for (let j = 1; j < subSections.length; j++) {
      const subSection = subSections[j].trim();
      if (!subSection) continue;
      
      const subSectionLines = subSection.split('\n');
      const subSectionTitle = subSectionLines[0].trim();
      const subSectionContent = subSectionLines.slice(1).join('\n').trim();
      
      // Create subsection slide
      const subSlide = pres.addSlide();
      
      // Add section marker
      subSlide.addText(sectionTitle, { 
        x: 0.5, 
        y: 0.3, 
        w: '90%', 
        h: 0.4,
        align: 'left',
        color: '6B7280', // gray-500
        fontFace: 'Arial',
        fontSize: 14
      });
      
      // Add subsection title
      subSlide.addText(subSectionTitle, { 
        x: 0.5, 
        y: 0.8, 
        w: '90%', 
        h: 0.8,
        align: 'left',
        color: '2563EB', // blue-600
        fontFace: 'Arial',
        fontSize: 28,
        bold: true
      });
      
      // Add accent line
      subSlide.addShape(pptxgen.ShapeType.rect, { 
        x: 0.5, 
        y: 1.7, 
        w: 2.5, 
        h: 0.08,
        fill: { color: '2563EB' }
      });
      
      // Extract bullet points for the subsection
      const bulletPoints = extractBulletPoints(subSectionContent);
      
      if (bulletPoints.length > 0) {
        subSlide.addText(bulletPoints.map(point => point.trim()), { 
          x: 0.5, 
          y: 2.2, 
          w: '90%', 
          h: 5,
          align: 'left',
          color: '000000',
          fontFace: 'Arial',
          fontSize: 18,
          bullet: true
        });
      } else {
        // If no bullet points, add paragraphs
        const paragraphs = subSectionContent.split('\n\n').filter(Boolean);
        
        subSlide.addText(paragraphs.join('\n\n'), { 
          x: 0.5, 
          y: 2.2, 
          w: '90%', 
          h: 5,
          align: 'left',
          color: '000000',
          fontFace: 'Arial',
          fontSize: 18
        });
      }
    }
  }
  
  // Add closing slide
  const closingSlide = pres.addSlide();
  
  closingSlide.background = { 
    color: '2563EB', // blue-600
    type: 'solid' 
  };
  
  closingSlide.addText('Thank You', { 
    x: 0.5, 
    y: 2.5, 
    w: '90%', 
    h: 1.5,
    align: 'center',
    color: 'FFFFFF',
    fontFace: 'Arial',
    fontSize: 44,
    bold: true
  });
  
  closingSlide.addText('Questions & Discussion', { 
    x: 0.5, 
    y: 4, 
    w: '90%', 
    h: 0.8, 
    align: 'center',
    color: 'FFFFFF',
    fontFace: 'Arial',
    fontSize: 24
  });
}

/**
 * Extract bullet points from markdown text
 * 
 * @param text Markdown text
 * @returns Array of bullet points
 */
function extractBulletPoints(text: string): string[] {
  const lines = text.split('\n');
  const bulletPoints: string[] = [];
  
  for (const line of lines) {
    // Match markdown bullet points (- or * or numbered list items)
    if (line.trim().match(/^[-*]\s+/) || line.trim().match(/^\d+\.\s+/)) {
      // Remove the bullet point marker
      const content = line.trim().replace(/^[-*]\s+/, '').replace(/^\d+\.\s+/, '');
      bulletPoints.push(content);
    }
  }
  
  return bulletPoints;
}